# Optional: Use this only if you want SQLite in a container
# Otherwise, the bot will create a local SQLite file automatically

services:
  # Volume for persistent data
  data:
    image: busybox
    volumes:
      - bot_data:/data
    command: "true"

volumes:
  bot_data:
    driver: local